Liber/Liber/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taxi.urls')),
    path('food/cart/', include('foodcart.urls')),
    path('food/', include('food.urls', namespace='food')),
    path('product/', include('product.urls')),
    path('cargo/', include('cargo.urls')),
    path('harw/', include('harw.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Liber/cargo/urls.py
from django.urls import path
from .  import views

urlpatterns = [
    path('', views.cargo, name='cargo'),
]

Liber/food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.restaurant_list, name='restaurant_list'),
    path('<slug:slug_restaurant>/', views.dish_list, name='dish_list'),
    path('<slug:slug_restaurant>/add', views.dish_list, name='dish_add'),
    path('<slug:slug_restaurant>/<slug:slug_dish>/', views.dish_detail, name='dish_detail')
]

Liber/foodcart/urls.py
from django.urls import path
from . import views


app_name = 'foodcart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:dish_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:dish_id>/', views.cart_remove, name='cart_remove'),
]

Liber/harw/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.harw, name='harw'),
]

Liber/product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.product, name='product'),
]

Liber/taxi/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Liber/cargo/models.py
from django.db import models

# Create your models here.

Liber/food/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(verbose_name='Название тега: ', max_length=200)
    slug_tag = models.SlugField(unique=True)
    img = models.ImageField(verbose_name='Изображение: ', upload_to='static/img/food/tags/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Restaurant(models.Model):
    name = models.CharField(verbose_name='Название ресторана: ', max_length=200)
    slug_restaurant = models.SlugField(unique=True)
    img = models.ImageField(verbose_name='Изображение: ', upload_to='static/img/food/restaurants/')
    description = models.TextField(verbose_name='Описание: ')
    rating = models.DecimalField(verbose_name='Рейтинг: ', max_digits=2, decimal_places=1)
    time_delivery = models.IntegerField(verbose_name='Время доставки: ')
    tags = models.ManyToManyField('Tag', verbose_name='Теги: ', related_name='tag')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ресторан'
        verbose_name_plural = 'Рестораны'


class DishCategory(models.Model):
    name = models.CharField(verbose_name='Название категории: ', max_length=200)
    slug_dishcategory = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория блюд'
        verbose_name_plural = 'Категории блюд'


class Dish(models.Model):
    name = models.CharField(verbose_name='Название блюда: ', max_length=200)
    slug_dish = models.SlugField(unique=True)
    img = models.ImageField(verbose_name='Изображение: ', upload_to='static/img/food/dishes/')
    description = models.TextField(verbose_name='Описание: ')
    restaurant = models.ForeignKey('Restaurant', verbose_name='Ресторан: ', related_name='restaurant',
                                   on_delete=models.PROTECT)
    category = models.ForeignKey('DishCategory', verbose_name='Категория блюда', related_name='category',
                                 on_delete=models.PROTECT)
    available = models.BooleanField(verbose_name='В наличии')
    price = models.IntegerField(verbose_name='Цена')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

Liber/foodcart/models.py
from django.db import models

# Create your models here.

Liber/harw/models.py
from django.db import models

# Create your models here.

Liber/taxi/models.py
from django.db import models

# Create your models here.

Liber/foodcart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOISES = [(i, str(i)) for i in range(1, 21)]

class CartAddDishForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOISES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Liber/cargo/views.py
from django.shortcuts import render


def cargo(request):
    return render(request, 'cargo/cargo.html')

Liber/food/views.py
from django.shortcuts import render, get_object_or_404
from .models import Tag, Restaurant, DishCategory, Dish


def restaurant_list(request):
    tag = Tag.objects.all()
    restaurant = Restaurant.objects.all()
    context = {
        'tag': tag,
        'restaurant': restaurant,
    }
    return render(request, 'food/restaurant_list.html', context)

def dish_list(request, slug_restaurant):
    restaurant = get_object_or_404(Restaurant, slug_restaurant__iexact=slug_restaurant)
    dishcat = DishCategory.objects.all()
    context = {
        'restaurant': restaurant,
        'dishcat': dishcat,
    }
    return render(request, 'food/dish_list.html', context)

def dish_detail(request, slug_restaurant, slug_dish):
    dish = get_object_or_404(Dish, slug_dish__iexact=slug_dish)
    restaurant = get_object_or_404(Restaurant, slug_restaurant__iexact=slug_restaurant)
    context = {
        'dish': dish,
        'restaurant': restaurant,
    }
    return render(request, 'food/dish_detail.html', context)

Liber/foodcart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from food.models import Dish
from .cart import Cart
from .forms import CartAddDishForm


@require_POST
def cart_add(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    form = CartAddDishForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(dish=dish, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('foodcart:cart_detail')

def cart_remove(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.remove(dish)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'foodcart/fdd.html', context)

Liber/harw/views.py
from django.shortcuts import render


def harw(request):
    return render(request, 'harw/harw.html')

Liber/product/views.py
from django.shortcuts import render


def product(request):
    return render(request, 'product/product.html')

Liber/taxi/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'taxi/index.html')

Liber/cargo/templates/cargo/cargo.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Liber - Заказ грузового автомобиля онлайн{% endblock %}
{% block content %}
{% include 'header.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="slider col-12">
            <div class="fotorama" data-width="100%" data-ratio="16/3" data-nav="false" data-autoplay="true"
                 data-loop="true">
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modules row">
        <a class="module" href="/">
            <div class="text-center">
                <img src="{% static 'img/taxi.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Такси</h4>
            </div>
        </a>
        <a class="module" href="/food">
            <div class="text-center">
                <img src="{% static 'img/food.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Еда</h4>
            </div>
        </a>
        <a class="module" href="/product">
            <div class="text-center">
                <img src="{% static 'img/product.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Продукты</h4>
            </div>
        </a>
        <a class="module_selected" href="/cargo">
            <div class="text-center">
                <img src="{% static 'img/cargo.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Грузовики</h4>
            </div>
        </a>
        <a class="module" href="/harw">
            <div class="text-center">
                <img src="{% static 'img/harw.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Спецтехника</h4>
            </div>
        </a>
    </div>
    <div class="row">
        <div class="taxi_order col-4">
            <h1 class="text-center">Заказ грузовика</h1>
            <h4>Выберите свое местонахождение</h4>
            <input type="text" class="form-control">
            <h4>Выберите место назначения</h4>
            <input type="text" class="form-control">
            <h4>Выберите грузоподъемность</h4>
            <div class="price">
                <input type="radio" name="price" id="eco">
                <label for="eco">
                    <h5 class="text-center">До 500кг</h5>
                </label>
            </div>
            <div class="price">
                <input type="radio" name="price" id="stand" checked>
                <label for="stand">
                    <h5 class="text-center">500кг-1т</h5>
                </label>
            </div>
            <div class="price">
                <input type="radio" name="price" id="com">
                <label for="com">
                    <h5 class="text-center">Более 1т</h5>
                </label>
            </div>
            <div class="text-center">
                <a href="#" class='open-modal_modal' data-modal_modal="#modal_modal3">
                    <button class="btn order_submit">Заказать</button>
                </a>
            </div>

        </div>
        <div class="col-8">
            <script type="text/javascript" charset="utf-8" async
                    src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A909ddf8e0a29669ea04d8bc784ac183780c8d76b6d035fc3ead6b86e6572f9e8&amp;width=100%&amp;height=700&amp;lang=ru_RU&amp;scroll=false"></script>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

Liber/food/templates/food/dish_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'header.html' %}
<h1>Hello</h1>

<h1>{{dish.name}}</h1>
<h2>{{dish.description}}</h2>
<img src="{{dish.img.url}}" alt="">
{% include 'footer.html' %}
</body>
</html>

Liber/food/templates/food/dish_list.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}{{ restaurant.name }}{% endblock %}
{% block content %}
{% include 'header.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="slider col-12">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-3">
                        <h1>{{restaurant.name}}</h1>
                        <p>{{restaurant.description}}</p>
                        <img src="{{ restaurant.img.url }}" alt="" height="200">
                    </div>
                    <div class="col-1 offset-8">
                        <button class="btn slider_button"><h4>Перейти</h4></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modules row">
        <a class="module" href="/">
            <div class="text-center">
                <img src="{% static 'img/taxi.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Такси</h4>
            </div>
        </a>
        <a class="module_selected" href="/food">
            <div class="text-center">
                <img src="{% static 'img/food.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Еда</h4>
            </div>
        </a>
        <a class="module" href="/product">
            <div class="text-center">
                <img src="{% static 'img/product.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Продукты</h4>
            </div>
        </a>
        <a class="module" href="/cargo">
            <div class="text-center">
                <img src="{% static 'img/cargo.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Грузовики</h4>
            </div>
        </a>
        <a class="module" href="/harw">
            <div class="text-center">
                <img src="{% static 'img/harw.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Спецтехника</h4>
            </div>
        </a>
    </div>

    

    {% for d in restaurant.restaurant.all %}
    <h1>{{ d.category }}</h1>
    <div class="col-3">
        <a href="{{d.slug_dish}}/">
            <div class="restaurant">
                <img class="restaurant_img" src="{{d.img.url}}" alt="">
                <p class="restaurant_title">{{d.name}}</p>
                {% if d.available == True %}
                <p class="restaurant_rating">В наличии</p>
                {% else %}
                <p class="restaurant_rating">Нет в наличии</p>
                {% endif %}
                <p class="restaurant_categories">{{d.description}}</p>
                <p class="restaurant_rating">{{d.price}} сум</p>
                <form action="{% url 'foodcart:cart_add' d.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart" class="btn btn-success">
                </form>
            </div>
        </a>
    </div>
    <div style="width: 100%; height: 3px; background-color: #303030; margin: 30px 0 30px 0;"></div>
    {% endfor %}
</div>
{% include 'footer.html' %}
{% endblock %}

<!--TODO: remake list view (split on categories (category, list of dishes, next category))
    TODO: try regroup-->

Liber/food/templates/food/restaurant_list.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Liber - Заказ еды на дом и в офис онлайн{% endblock %}
{% block content %}
{% include 'header.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="slider col-12">
            <div class="fotorama" data-width="100%" data-ratio="16/3" data-nav="false" data-autoplay="true"
                 data-loop="true">
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modules row">
        <a class="module" href="/">
            <div class="text-center">
                <img src="{% static 'img/taxi.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Такси</h4>
            </div>
        </a>
        <a class="module_selected" href="/food">
            <div class="text-center">
                <img src="{% static 'img/food.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Еда</h4>
            </div>
        </a>
        <a class="module" href="/product">
            <div class="text-center">
                <img src="{% static 'img/product.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Продукты</h4>
            </div>
        </a>
        <a class="module" href="/cargo">
            <div class="text-center">
                <img src="{% static 'img/cargo.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Грузовики</h4>
            </div>
        </a>
        <a class="module" href="/harw">
            <div class="text-center">
                <img src="{% static 'img/harw.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Спецтехника</h4>
            </div>
        </a>
    </div>
    <div class="row justify-content-center">
        {% for tag in tag %}
        <a href="#" class="food_category">
            <img src="{{ tag.img.url }}" alt="{{ tag.name }}">
            <p class="text-center">{{ tag.name }}</p>
        </a>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-12">
            <h1 class="restaurants_title">Рестораны</h1>
        </div>
        {% for rest in restaurant %}
        <div class="col-xl-3 col-12">
            <a href="{{ rest.slug_restaurant }}/">
                <div class="restaurant">
                    <img class="restaurant_img" src="{{ rest.img.url }}" alt="">
                    <p class="restaurant_time">~ {{ rest.time_delivery }} мин</p>
                    <p class="restaurant_title">{{ rest.name }}</p>
                    <p class="restaurant_rating">Рейтинг: {{ rest.rating }}</p>
                    <p class="restaurant_categories">Категории: {% for cats in rest.tags.all %}*{{ cats.name }} {% endfor %}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

Liber/food/templates/foodcart/fdd.html
{% load static %}
{% block content %}
{% for item in cart %}
    {% with product=item.product %}
        <h1>{{ product.name }}</h1>
        <h3>{{ item.quantity }}</h3>
        <h3>Price: {{ item.price }}</h3>
        <h2>Total Price: {{ item.total_price }}</h2>
        <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
    {% endwith %}
{% endfor %}
<h1>Total: {{ cart.get_total_price }} </h1>
<a href="{% url 'food:dish_list' %}">Continue Shopping</a>
{% endblock %}

Liber/harw/templates/harw/harw.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Liber - Заказ спецтехники онлайн{% endblock %}
{% block content %}
{% include 'header.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="slider col-12">
            <div class="fotorama" data-width="100%" data-ratio="16/3" data-nav="false" data-autoplay="true"
                 data-loop="true">
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-3">
                                <h1>Lorem ipsum.</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate laborum
                                    accusantium atque optio sunt cum maiores aut. Enim eius ducimus molestias itaque
                                    veritatis atque, modi fugiat dolorem consequatur, mollitia, distinctio, dolore
                                    minus. At, deleniti accusamus delectus voluptatem enim illum optio aspernatur beatae
                                    sit nulla possimus quas vel sunt dolorem voluptate!</p>
                            </div>
                            <div class="col-1 offset-8">
                                <button class="btn slider_button"><h4>Перейти</h4></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modules row">
        <a class="module" href="/">
            <div class="text-center">
                <img src="{% static 'img/taxi.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Такси</h4>
            </div>
        </a>
        <a class="module" href="/food">
            <div class="text-center">
                <img src="{% static 'img/food.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Еда</h4>
            </div>
        </a>
        <a class="module" href="/product">
            <div class="text-center">
                <img src="{% static 'img/product.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Продукты</h4>
            </div>
        </a>
        <a class="module" href="/cargo">
            <div class="text-center">
                <img src="{% static 'img/cargo.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Грузовики</h4>
            </div>
        </a>
        <a class="module_selected" href="/harw">
            <div class="text-center">
                <img src="{% static 'img/harw.png' %}" alt="">
            </div>
            <div class="text-center">
                <h4>Спецтехника</h4>
            </div>
        </a>
    </div>
    <div class="row">
        <div class="taxi_order col-4">
            <h1 class="text-center">Заказ спецтехники</h1>
            <h4>Выберите свое местонахождение</h4>
            <input type="text" class="form-control">
            <h4>Выберите место назначения</h4>
            <input type="text" class="form-control">
            <h4>Выберите тип техники</h4>
            <div class="price">
                <input type="radio" name="price" id="eco">
                <label for="eco">
                    <h5 class="text-center">Кран</h5>
                </label>
            </div>
            <div class="price">
                <input type="radio" name="price" id="stand" checked>
                <label for="stand">
                    <h5 class="text-center">Бульдозер</h5>
                </label>
            </div>
            <div class="price">
                <input type="radio" name="price" id="com">
                <label for="com">
                    <h5 class="text-center">Эвакуатор</h5>
                </label>
            </div>
            <div class="text-center">
                <a href="#" class='open-modal_modal' data-modal_modal="#modal_modal3">
                    <button class="btn order_submit">Заказать</button>
                </a>
            </div>

        </div>
        <div class="col-8">
            <script type="text/javascript" charset="utf-8" async
                    src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A909ddf8e0a29669ea04d8bc784ac183780c8d76b6d035fc3ead6b86e6572f9e8&amp;width=100%&amp;height=700&amp;lang=ru_RU&amp;scroll=false"></script>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

Liber/taxi/templates/footer.html
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h6 class="text-center copyright">Liber - 2019. Все права защищены</h6>
            </div>
        </div>
    </div>
</footer>